spring.application.name=paratodos
spring.datasource.url=jdbc:postgresql://localhost:5432/paratodos
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret-base64=iws+iADdjBIXIcOc8VMNiq+LYuyUcIyYnHTLtKyRJMw=
app.jwt.expiration-ms=86400000