spring.application.name=paratodos
spring.datasource.url=jdbc:postgresql://localhost:5432/paratodos
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=false

app.jwt.secret-base64=iws+iADdjBIXIcOc8VMNiq+LYuyUcIyYnHTLtKyRJMw=
app.jwt.expiration-ms=86400000

# ---- Email (SMTP) para envio de codigo 2FA ----
# Gmail: use uma "Senha de app" (https://myaccount.google.com/apppasswords)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jpjerosch@gmail.com
spring.mail.password=xhfa ecdk otjx pfnu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=jpjerosch@gmail.com